services:
  mysql:
    image: mysql:8.4
    container_name: mysql-giofchar-db-84
    restart: always
    platform: linux/amd64
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - backend-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-giofchar-server
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      HOST_NAME: ${HOST_NAME}

      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_PORT: 3306

      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRES_IN: ${ACCESS_TOKEN_EXPIRES_IN}

      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRES_IN: ${REFRESH_TOKEN_EXPIRES_IN}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

      GEMINI_API_KEYS: ${GEMINI_API_KEYS}
      SESSION_SECRET: ${SESSION_SECRET}

      CLIENT_ORIGINS: ${CLIENT_ORIGINS}
      VNP_TMN_CODE: ${VNP_TMN_CODE}
      VNP_HASH_SECRET: ${VNP_HASH_SECRET}
      VNP_PAY_URL: ${VNP_PAY_URL}
      VNP_RETURN_URL: ${VNP_RETURN_URL}
      VNP_IPN_URL: ${VNP_IPN_URL}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-net

volumes:
  mysql_data:

networks:
  backend-net:
    driver: bridge
