const OUTBOX_PROCESSING_TIMEOUT_ERROR = "Processing timeout; job requeued";

const OUTBOX_ERROR_CODES = Object.freeze({
  EVENT_NOT_PROCESSING: "OUTBOX_EVENT_NOT_PROCESSING",
  CLAIM_COUNT_MISMATCH: "OUTBOX_CLAIM_COUNT_MISMATCH",
});

const OUTBOX_EVENT_TYPES = Object.freeze({
  ORDER_CREATED: "order.created",
});

const MAX_ATTEMPTS = 5;
const BASE_RETRY_DELAY_SECONDS = 30;
const MAX_RETRY_DELAY_SECONDS = 15 * 60;
const RECOVERY_STALE_AFTER_SECONDS = 30;

module.exports = {
  OUTBOX_ERROR_CODES,
  OUTBOX_EVENT_TYPES,
  OUTBOX_PROCESSING_TIMEOUT_ERROR,
  MAX_ATTEMPTS,
  BASE_RETRY_DELAY_SECONDS,
  MAX_RETRY_DELAY_SECONDS,
  RECOVERY_STALE_AFTER_SECONDS,
};
