const OUTBOX_PROCESSING_TIMEOUT_ERROR =
  "Processing timeout; job requeued";

const OUTBOX_ERROR_CODES = Object.freeze({
  EVENT_NOT_PROCESSING: "OUTBOX_EVENT_NOT_PROCESSING",
  CLAIM_COUNT_MISMATCH: "OUTBOX_CLAIM_COUNT_MISMATCH",
});

const OUTBOX_EVENT_TYPES = Object.freeze({
  ORDER_CREATED: "order.created",
});

module.exports = {
  OUTBOX_ERROR_CODES,
  OUTBOX_EVENT_TYPES,
  OUTBOX_PROCESSING_TIMEOUT_ERROR,
};
